const betfairLinks = [
  //"https://www.betfair.it/sport/football/argentina-primera-division/67387",
  //   "https://www.betfair.it/sport/football/austria-bundesliga/10479956",
  //   "https://www.betfair.it/sport/football/brasile-serie-a/13",
  //   "https://www.betfair.it/sport/football/francia-ligue-1/55",
  //   "https://www.betfair.it/sport/football/francia-ligue-2/57",
  //   "https://www.betfair.it/sport/football/germania-bundesliga/59",
  //   "https://www.betfair.it/sport/football/germania-bundesliga-2/61",
  //   "https://www.betfair.it/sport/football/giappone-j-league/89",
  //   "https://www.betfair.it/sport/football/giappone-j-league-2/1062024",
  //   "https://www.betfair.it/sport/football/inghilterra-championship/7129730",
  //   "https://www.betfair.it/sport/football/inghilterra-league-one/35",
  //   "https://www.betfair.it/sport/football/inghilterra-premier-league/10932509",
  //  "https://www.betfair.it/sport/football/italia-serie-a/81",
  //"https://www.betfair.it/sport/football/italia-serie-b/12199689",
  "https://www.betfair.it/sport/football/australia-npl-tasmania/12013782",
  //   "https://www.betfair.it/sport/football/olanda-eerste-divisie/11",
  //   "https://www.betfair.it/sport/football/olanda-eredivisie/9404054",
  //   "https://www.betfair.it/sport/football/portogallo-primeira-liga/99",
  //   "https://www.betfair.it/sport/football/russia-premier-league/101",
  //   "https://www.betfair.it/sport/football/spagna-la-liga/117",
  //   "https://www.betfair.it/sport/football/spagna-segunda-division/12204313",
  //   "https://www.betfair.it/sport/football/uefa-champions-league/228",
  //   "https://www.betfair.it/sport/football/uefa-europa-league/2005",
  //   "https://www.betfair.it/sport/football/uefa-nations-league/11984200",
  //"https://www.betfair.it/sport/football/usa-major-league-soccer/141",
];
module.exports = betfairLinks;
