const betterLinks = [
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/mondo/qualifmondiali.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/europa/championsleague.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/europa/europaleague.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/europa/europa-uefanationsleague.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/italia/seriea",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/italia/serieb.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/inghilterra/premierleague.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/inghilterra/championship.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/inghilterra/leagueone.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/spagna/primeradivision.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/spagna/segundadivision.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/germania/bundesliga.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/germania/2bundesliga.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/francia/ligue1.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/francia/ligue2.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/argentina/primeradivision.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/austria/bundesliga.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/brasile/seriea.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/giappone/jleague.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/giappone/jleague2.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/olanda/eredivisie.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/olanda/eerstedivisie.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/portogallo/primeiraliga.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/russia/idivisione.html",
  "https://www.lottomatica.it/scommesse/avvenimenti/calcio/statiuniti/majorleaguesoccer.html",
];

module.exports = betterLinks;
