const tournaments = {
  qualifmondiali: "Qualificazioni Mondiali",
  championsleague: "Champions League",
  europaleague: "Europa League",
  "europa-uefanationsleagu": "Nations League",
  seriea: "Serie A",
  serieb: "Serie B",
  premierleague: "Premier League",
  championship: "Championship",
  leagueone: "League One",
  primeradivision: "Primera Division",
  segundadivision: "Segunda Division",
  bundesliga: "Bundesliga",
  "2bundesliga": "2. Bundesliga",
  ligue1: "Ligue 1",
  ligue2: "Ligue 2",
  primeradivision: "Primera National",
  jleague: "J1 League",
  jleague2: "J2 League",
  eredivisie: "Eredivisie",
  eerstedivisie: "Eerstedivisie",
  primeiraliga: "Primeira Liga",
  idivisione: "Premier Ligue",
  majorleaguesoccer: "MSL",
};
module.exports = tournaments;
