const marathonbetLinks = [
  "https://www.marathonbet.it/it/popular/Football/Italy/Serie+A+-+22434",
  // "https://www.marathonbet.it/it/popular/Football/Italy/Serie+B+-+46723",
  // "https://www.marathonbet.it/it/popular/Football/England/Premier+League+-+21520",
  // "https://www.marathonbet.it/it/popular/Football/England/Championship+-+22807",
  // "https://www.marathonbet.it/it/popular/Football/England/League+1+-+22808",
  // "https://www.marathonbet.it/it/popular/Football/Germany/Bundesliga+-+22436",
  // "https://www.marathonbet.it/it/popular/Football/Germany/Bundesliga+2+-+42528",
  // "https://www.marathonbet.it/it/popular/Football/Spain/Primera+Division+-+8736",
  // "https://www.marathonbet.it/it/popular/Football/Spain/Segunda+Division+-+48300",
  // "https://www.marathonbet.it/it/popular/Football/France/Ligue+1+-+21533",
  // "https://www.marathonbet.it/it/popular/Football/France/Ligue+2+-+46785",
  // "https://www.marathonbet.it/it/popular/Football/Netherlands/Eredivisie+-+38090",
  // "https://www.marathonbet.it/it/popular/Football/Netherlands/Eerste+Divisie+-+345004",
  // "https://www.marathonbet.it/it/popular/Football/Portugal/Primeira+Liga+-+43058",
  // "https://www.marathonbet.it/it/popular/Football/Portugal/Segunda+Liga+-+344256",
  // "https://www.marathonbet.it/it/popular/Football/Argentina/Primera+Division+-+10803",
  // "https://www.marathonbet.it/it/popular/Football/Austria/Bundesliga+-+46715",
  // "https://www.marathonbet.it/it/popular/Football/Japan/J.League/Division+1+-+441958",
  // "https://www.marathonbet.it/it/popular/Football/Japan/J.League/Division+2+-+420995",
  // "https://www.marathonbet.it/it/popular/Football/Russia/Premier+League+-+22433",
  // "https://www.marathonbet.it/it/popular/Football/USA/MLS+-+138152",
];

module.exports = marathonbetLinks;
