const betalandLinks = [
  "https://www.betaland.it/sport/calcio/italia/serie-a-OIA-scommesse-sportive-online",
  "https://www.betaland.it/sport/calcio/serie-b_1_31_34",
  "https://www.betaland.it/sport/calcio/inghilterra/premierleague-OIA-scommesse-sportive-online",
  "https://www.betaland.it/sport/calcio/championship_1_1_2",
  "https://www.betaland.it/sport/calcio/league-one_1_1_3",
  "https://www.betaland.it/sport/calcio/germania/bundesliga-OIA-scommesse-sportive-online",
  "https://www.betaland.it/sport/calcio/2.bundesliga_1_30_41",
  "https://www.betaland.it/sport/calcio/spagna/liga-OIA-scommesse-sportive-online",
  "https://www.betaland.it/sport/calcio/laliga-2_1_32_37",
  "https://www.betaland.it/sport/calcio/ligue-1_1_7_4",
  "https://www.betaland.it/sport/calcio/ligue-2_1_7_19",
  "https://www.betaland.it/sport/calcio/eredivisie_1_35_39",
  "https://www.betaland.it/sport/calcio/eerste-divisie_1_35_40",
  "https://www.betaland.it/sport/calcio/primeira-liga_1_44_52",
  "https://www.betaland.it/sport/calcio/segunda-liga_1_44_280",
  "https://www.betaland.it/sport/calcio/super-lig_1_46_62",
  "https://www.betaland.it/sport/calcio/superliga_1_48_68",
  "https://www.betaland.it/sport/calcio/bundesliga_1_17_29",
  "https://www.betaland.it/sport/calcio/j.league_1_52_82",
  "https://www.betaland.it/sport/calcio/j.league-2_1_52_3034",
  "https://www.betaland.it/sport/calcio/premier-league_1_21_53",
  "https://www.betaland.it/sport/calcio/major-league-soccer_1_26_18",
];

module.exports = betalandLinks;
