const eurobetLinks = [
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/it-serie-a/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/it-serie-b1",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/ing-premier-league/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/ing-championship1/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/ing-league-one2/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/de-bundesliga/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/de-2-bundesliga1/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/es-liga/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/es-liga-adelante/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/fr-ligue-1/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/fr-ligue-2/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/nl-eredivisie1/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/nl-eerste-divisie/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/pt-primeira-liga/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/pt-liga-de-honra/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/tr-super-lig-64/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/ar-primera-division1/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/at-bundesliga/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/jp-j-league/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/jp-j2-league/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/ru-premier-league/",
  "https://www.eurobet.it/it/scommesse/?splash=false#!/calcio/us-mls/",
];

module.exports = eurobetLinks;
